"""initial

Revision ID: c0af5086363a
Revises:
Create Date: 2024-07-07 19:46:19.617444

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c0af5086363a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "predicted_trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("open_price", sa.Float(), nullable=True),
        sa.Column("take_price", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_predicted_trades_id"), "predicted_trades", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_predicted_trades_symbol"), "predicted_trades", ["symbol"], unique=False
    )
    op.create_table(
        "stock_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("volume", sa.Integer(), nullable=True),
        sa.Column("vwap", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "date", name="symbol_date_unique"),
    )
    op.create_index(op.f("ix_stock_data_date"), "stock_data", ["date"], unique=False)
    op.create_index(op.f("ix_stock_data_id"), "stock_data", ["id"], unique=False)
    op.create_index(
        op.f("ix_stock_data_symbol"), "stock_data", ["symbol"], unique=False
    )
    op.create_table(
        "tickers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("market_cap", sa.Integer(), nullable=True),
        sa.Column("gross_margin_pct", sa.Float(), nullable=True),
        sa.Column("net_margin_pct", sa.Float(), nullable=True),
        sa.Column("trailing_pe", sa.Float(), nullable=True),
        sa.Column("forward_pe", sa.Float(), nullable=True),
        sa.Column("industry", sa.String(), nullable=True),
        sa.Column("is_tradeable", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tickers_id"), "tickers", ["id"], unique=False)
    op.create_index(op.f("ix_tickers_name"), "tickers", ["name"], unique=False)
    op.create_index(op.f("ix_tickers_symbol"), "tickers", ["symbol"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tickers_symbol"), table_name="tickers")
    op.drop_index(op.f("ix_tickers_name"), table_name="tickers")
    op.drop_index(op.f("ix_tickers_id"), table_name="tickers")
    op.drop_table("tickers")
    op.drop_index(op.f("ix_stock_data_symbol"), table_name="stock_data")
    op.drop_index(op.f("ix_stock_data_id"), table_name="stock_data")
    op.drop_index(op.f("ix_stock_data_date"), table_name="stock_data")
    op.drop_table("stock_data")
    op.drop_index(op.f("ix_predicted_trades_symbol"), table_name="predicted_trades")
    op.drop_index(op.f("ix_predicted_trades_id"), table_name="predicted_trades")
    op.drop_table("predicted_trades")
    # ### end Alembic commands ###
